using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using DAFP.TOOLS.Common.Utill;
using ModestTree;
using NUnit.Framework;
using PixelRouge.Inspector.Extensions;
using UnityEngine;

namespace DAFP.TOOLS.ECS.BigData
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using UnityEngine;

    // unified member info wrapper to handle both fields and properties
    public static class StatInjector
    {
        public static bool DEBUG = false;

        // ── StatMember — unified wrapper for FieldInfo and PropertyInfo ───────────

        private readonly struct StatMember
        {
            private readonly FieldInfo _field;
            private readonly PropertyInfo _property;

            public StatMember(FieldInfo field)
            {
                _field = field;
                _property = null;
            }

            public StatMember(PropertyInfo property)
            {
                _property = property;
                _field = null;
            }

            public string Name => _field?.Name ?? _property?.Name;
            public Type MemberType => _field?.FieldType ?? _property?.PropertyType;
            public bool IsField => _field != null;

            public object GetValue(object source)
                => _field != null ? _field.GetValue(source) : _property?.GetValue(source);

            public void SetValue(object source, object value)
            {
                if (_field != null)
                {
                    _field.SetValue(source, value);
                }
                else if (_property != null)
                {
                    if (_property.CanWrite)
                    {
                        _property.SetValue(source, value);
                    }
                    else
                    {
                        // Fallback: Find the hidden backing field generated by the C# compiler 
                        // for getter-only auto-properties (e.g., "<Zoom>k__BackingField")
                        var backingField = source.GetType().GetField($"<{_property.Name}>k__BackingField",
                            BindingFlags.Instance | BindingFlags.NonPublic);

                        if (backingField != null)
                        {
                            backingField.SetValue(source, value);
                        }
                        else if (DEBUG)
                        {
                            UnityEngine.Debug.LogWarning(
                                $"StatInjector: Failed to inject {_property.Name}. It lacks both a setter and a backing field.");
                        }
                    }
                }
            }

            public T GetCustomAttribute<T>() where T : Attribute
                => _field != null
                    ? _field.GetCustomAttribute<T>()
                    : _property?.GetCustomAttribute<T>();

            public bool HasAttribute(Type attrType)
                => _field != null
                    ? _field.HasAttribute(attrType)
                    : _property?.GetCustomAttributes(attrType, true).Length > 0;

            public bool Equals(StatMember other)
                => _field == other._field && _property == other._property;
        }

        // ── Public API ────────────────────────────────────────────────────────────

        public static void InjectStats(IHaveStats entity, object[] additionalSources)
        {
            if (entity?.Stats == null)
                return;

            if (extract_injectable_fields(entity, additionalSources, out var _refined, out var _fieldSources))
                return;

            foreach (var _valueTuple in _refined)
            {
                var _source = (_fieldSources != null && _fieldSources.TryGetValue(_valueTuple.member, out var __s))
                    ? __s
                    : (object)entity;
                inject_stat(_valueTuple, entity, _source);
            }
        }

        public static void FixStats(IHaveStats entity, object[] additionalSources)
        {
            if (entity?.Stats == null)
                return;

            if (extract_declared_stats(entity, additionalSources, out var _refined, out _))
                return;

            apply_flat_fix();

            foreach (var _valueTuple in _refined)
            {
                var _member = _valueTuple.member;
                var _naming = $"[{_valueTuple.attr.StatName}]/({_member.Name})";

                if (DEBUG)
                    Debug.Log($"StatInjector: trying to fix  {_naming} :: ");

                PathBuilder _path = null;
                try
                {
                    _path = new PathBuilder(_valueTuple.attr.StatName);
                }
                catch (Exception _e)
                {
                    if (DEBUG)
                        Debug.LogError($"StatInjector: failed to build path from {_naming} :: {_e}");
                    return;
                }

                if (entity.Stats.Has(_path))
                    continue;

                if (_path.GetTotalDepth() == 0)
                {
                    simple_resolve_stat(entity, _valueTuple, _naming);
                    continue;
                }

                var _data = _path.IterateProgressivePaths().ToArray();
                var _dataOnlyNames = _path.IterateRootToLeaf().ToArray();

                resolve_stat_dependencies(_data, _dataOnlyNames, _member, _valueTuple);

                var _leafStat = try_generate_stat(_valueTuple);
                entity.Stats.Add(_path, _leafStat);
            }

            void apply_flat_fix()
            {
                foreach (var _valueTuple in _refined.Where(t =>
                             new PathBuilder(t.attr.StatName).GetTotalDepth() == 0))
                {
                    var _naming = $"[{_valueTuple.attr.StatName}]/({_valueTuple.member.Name})";
                    simple_resolve_stat(entity, _valueTuple, _naming);
                }
            }

            void resolve_stat_dependencies(string[] _data, string[] _dataOnlyNames, StatMember _member,
                (StatMember member, DeclareStatAttribute attr) _valueTuple)
            {
                for (int _i = 0; _i < _data.Length - 1; _i++)
                {
                    var _entryPath = _data[_i];

                    if (entity.Stats.Has(new PathBuilder(_entryPath)))
                        continue;

                    var _foundMatchInDeclared = _refined.FirstOrDefault(t => t.attr.StatName == _entryPath);
                    if (!_foundMatchInDeclared.Equals(default))
                    {
                        var _stat = try_generate_stat(_foundMatchInDeclared);
                        entity.Stats.Add(new PathBuilder(_entryPath), _stat);
                        continue;
                    }

                    var _auto = (member: _member,
                        attr: new DeclareStatAttribute(_entryPath, _valueTuple.attr.FallbackObject));
                    var _autoStat = try_generate_stat(_auto);
                    entity.Stats.Add(new PathBuilder(_entryPath), _autoStat);
                }
            }
        }

        // ── Extraction ────────────────────────────────────────────────────────────

        private static bool extract_declared_stats(IEntity entity, object[] additionalSources,
            out (StatMember member, DeclareStatAttribute attr)[] _refined)
            => extract_declared_stats(entity, additionalSources, out _refined, out _);

        private static bool extract_declared_stats(object entity, object[] additionalSources,
            out (StatMember member, DeclareStatAttribute attr)[] _refined,
            out Dictionary<StatMember, object> fieldSources)
        {
            object[] _sources = additionalSources.Concat(new[] { entity }).ToArray();
            var _rawMembers = new List<StatMember>();
            fieldSources = new Dictionary<StatMember, object>();

            foreach (var _source in _sources)
            {
                var _fields = _source.GetAllFields(info => info.HasAttribute(typeof(DeclareStatAttribute)))
                    .Select(f => new StatMember(f));

                var _properties = _source.GetType()
                    .GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                    .Where(p => p.GetCustomAttribute<DeclareStatAttribute>() != null)
                    .Select(p => new StatMember(p));

                foreach (var _m in _fields.Concat(_properties))
                {
                    if (!_rawMembers.Any(x => x.Equals(_m)))
                        _rawMembers.Add(_m);
                    if (!fieldSources.ContainsKey(_m))
                        fieldSources[_m] = _source;
                }
            }

            if (_rawMembers.Count == 0)
            {
                _refined = null;
                fieldSources = null;
                return true;
            }

            _refined = _rawMembers
                .Select(m => (m, m.GetCustomAttribute<DeclareStatAttribute>()))
                .ToArray();
            return false;
        }

        private static bool extract_injectable_fields(object entity, object[] additionalSources,
            out (StatMember member, string statName)[] _refined,
            out Dictionary<StatMember, object> fieldSources)
        {
            object[] _sources = additionalSources.Concat(new[] { entity }).ToArray();
            var _rawMembers = new List<StatMember>();
            fieldSources = new Dictionary<StatMember, object>();

            foreach (var _source in _sources)
            {
                var _fields = _source.GetAllFields(info =>
                        info.HasAttribute(typeof(DeclareStatAttribute)) ||
                        info.HasAttribute(typeof(InjectStatAttribute)))
                    .Select(f => new StatMember(f));

                var _properties = _source.GetType()
                    .GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                    .Where(p => p.GetCustomAttribute<DeclareStatAttribute>() != null ||
                                p.GetCustomAttribute<InjectStatAttribute>() != null)
                    .Select(p => new StatMember(p));

                foreach (var _m in _fields.Concat(_properties))
                {
                    if (!_rawMembers.Any(x => x.Equals(_m)))
                        _rawMembers.Add(_m);
                    if (!fieldSources.ContainsKey(_m))
                        fieldSources[_m] = _source;
                }
            }

            if (_rawMembers.Count == 0)
            {
                _refined = null;
                fieldSources = null;
                return true;
            }

            _refined = _rawMembers
                .Select(m =>
                {
                    var _decl = m.GetCustomAttribute<DeclareStatAttribute>();
                    if (_decl != null) return (m, _decl.StatName);
                    var _inj = m.GetCustomAttribute<InjectStatAttribute>();
                    return (m, _inj.StatName);
                })
                .ToArray();
            return false;
        }

        // ── Injection ─────────────────────────────────────────────────────────────

        private static void inject_stat((StatMember member, string statName) field, IHaveStats entity, object source)
        {
            var _path = new PathBuilder(field.statName);
            if (entity.Stats.Has(_path, out var _statBase))
            {
                field.member.SetValue(source, _statBase);
                return;
            }

            var _declare = field.member.GetCustomAttribute<DeclareStatAttribute>();
            if (_declare != null)
            {
                field.member.SetValue(source, try_generate_stat((field.member, _declare)));
                return;
            }

            var _naming = $"[{field.statName}] :: ({field.member.Name})";
            throw new Exception($"StatInjector: failed to inject: {_naming} ::");
        }

        // ── Stat Generation ───────────────────────────────────────────────────────

        private static IStatBase try_generate_stat((StatMember member, DeclareStatAttribute attr) field)
        {
            IStatBase _stat = null;
            try
            {
                _stat = generate_stat_from_info(field);
            }
            catch (Exception _e)
            {
                if (DEBUG)
                    Debug.LogError($"StatInjector: failed to generate stat from info {field.attr.StatName} :: {_e}");
            }

            return _stat;
        }

        private static void simple_resolve_stat(IHaveStats entity,
            (StatMember member, DeclareStatAttribute attr) valueTuple,
            string naming)
        {
            if (check_field(valueTuple, entity.Stats))
            {
                try
                {
                    entity.Stats.Add(generate_stat_from_info(valueTuple));
                }
                catch (Exception _e)
                {
                    if (DEBUG)
                        Debug.LogError($"StatInjector: failed to generate stat from info {naming} :: {_e}");
                }
            }
        }

        private static bool check_field((StatMember member, DeclareStatAttribute attr) field, IStatContainer stats)
        {
            PathBuilder _path = null;
            var _naming = $"[{field.attr.StatName}]/({field.member.Name})";
            try
            {
                _path = new PathBuilder(field.attr.StatName);
            }
            catch (Exception _ex)
            {
                if (DEBUG)
                    Debug.Log($"StatInjector: field resolution failed {_naming} :: " + _ex.Message);
                return false;
            }

            if (stats.Has(_path))
                return false;

            return true;
        }

        private static IStatBase generate_stat_from_info((StatMember member, DeclareStatAttribute attr) field)
        {
            PathBuilder _path = null;
            try
            {
                _path = new PathBuilder(field.attr.StatName);
            }
            catch (Exception _e)
            {
                Debug.LogError($"StatInjector: stat {field.member.Name} has invalid name:: {_e}");
                throw;
            }

            var _naming = $"[{field.attr.StatName}]/({field.member.Name})";
            if (DEBUG) Debug.Log($"StatInjector: stat {_naming} :: ");

            if (field.member.MemberType is { IsGenericType: true })
            {
                Type _gen = field.member.MemberType.GenericTypeArguments[0];
                Type _boardType;
                switch (Type.GetTypeCode(_gen))
                {
                    case TypeCode.Boolean:
                        _boardType = typeof(DAFP.TOOLS.ECS.BigData.Common.BoolBoard);
                        break;
                    default:
                        _boardType = typeof(GenericWhiteBoard<>).MakeGenericType(_gen);
                        break;
                }

                var _inst = (IStatBase)Activator.CreateInstance(_boardType);
                configure_stat_defaults(field, _inst, _path, _gen);
                return _inst;
            }

            IStatBase _stat = (IStatBase)Activator.CreateInstance(field.member.MemberType);
            configure_stat_defaults(field, _stat, _path, null);
            return _stat;
        }

        private static void configure_stat_defaults(
            (StatMember member, DeclareStatAttribute attr) field,
            IStatBase inst, PathBuilder path, Type genericsType)
        {
            inst.Name = path.GetLeaf();

            object fallback = field.attr.FallbackObject;
            if (fallback == null) return;

            Type targetType = genericsType ?? field.member.MemberType;

            object converted = targetType.IsInstanceOfType(fallback)
                ? fallback
                : try_convert(fallback, targetType);


            // Compare against the type's zero to decide min vs max
            object zero = targetType.IsValueType ? Activator.CreateInstance(targetType) : null;
            int cmp = CompareAs(converted, zero, targetType);

            if (cmp < 0)
                inst.SetAbsoluteMin(converted);
            else if (cmp > 0)
                inst.SetAbsoluteMax(converted);

            inst.SetAbsoluteDefault(converted);
            inst.SetAbsoluteValue(converted);
        }

        // ── Utilities ─────────────────────────────────────────────────────────────

        public static object try_convert(object value, Type targetType)
        {
            if (value == null)
                return targetType.IsValueType ? Activator.CreateInstance(targetType) : null;

            try
            {
                if (value is IConvertible)
                    return Convert.ChangeType(value, targetType);

                var _convertMethod = targetType.GetMethod("op_Implicit", new[] { value.GetType() })
                                     ?? targetType.GetMethod("op_Explicit", new[] { value.GetType() });
                if (_convertMethod != null)
                    return _convertMethod.Invoke(null, new[] { value });

                var _converter = System.ComponentModel.TypeDescriptor.GetConverter(targetType);
                if (_converter.CanConvertFrom(value.GetType()))
                    return _converter.ConvertFrom(value);

                var _constructor = targetType.GetConstructor(new[] { value.GetType() });
                if (_constructor != null)
                    return _constructor.Invoke(new[] { value });

                if (value is string _str)
                {
                    var _parseMethod = targetType.GetMethod("Parse", new[] { typeof(string) });
                    if (_parseMethod != null && _parseMethod.IsStatic)
                        return _parseMethod.Invoke(null, new object[] { _str });
                }
            }
            catch
            {
            }

            return targetType.IsValueType ? Activator.CreateInstance(targetType) : null;
        }

        private static int CompareAs(object a, object b, Type gen)
        {
            if (a == null && b == null) return 0;
            if (a == null) return -1;
            if (b == null) return 1;

            var _comparerType = typeof(Comparer<>).MakeGenericType(gen);
            var _defaultProp = _comparerType.GetProperty("Default");
            var _defaultComparer = _defaultProp.GetValue(null);
            var _compareMethod = _comparerType.GetMethod("Compare", new[] { gen, gen });
            return (int)_compareMethod.Invoke(_defaultComparer, new[] { a, b });
        }

        // ── PathBuilder ───────────────────────────────────────────────────────────

        public class PathBuilder
        {
            private List<string> segments;
            private int currentIndex;
            private static readonly char[] SEPARATORS = { '/', '\\', '.' };

            public PathBuilder(string path, char[] separators = null)
            {
                if (string.IsNullOrWhiteSpace(path))
                    throw new ArgumentException("Path cannot be null or empty", nameof(path));

                var _separators = separators ?? SEPARATORS;
                segments = path.Split(_separators, StringSplitOptions.RemoveEmptyEntries).ToList();

                if (segments.Count == 0)
                    throw new ArgumentException("Path must contain at least one segment", nameof(path));

                currentIndex = segments.Count - 1;
            }

            public string GetRoot() => segments[0];
            public string GetLeaf() => segments[^1];
            public string GetCurrent() => segments[currentIndex];

            public PathBuilder MoveUp(int steps = 1)
            {
                currentIndex = Math.Max(0, currentIndex - steps);
                return this;
            }

            public PathBuilder MoveDown(int steps = 1)
            {
                currentIndex = Math.Min(segments.Count - 1, currentIndex + steps);
                return this;
            }

            public PathBuilder MoveToRoot()
            {
                currentIndex = 0;
                return this;
            }

            public PathBuilder MoveToLeaf()
            {
                currentIndex = segments.Count - 1;
                return this;
            }

            public int GetDepth() => currentIndex;
            public int GetTotalDepth() => segments.Count - 1;

            public string GetPathToCurrent() => string.Join(SEPARATORS[0], segments.Take(currentIndex + 1));
            public string GetFullPath() => string.Join(SEPARATORS[0], segments);
            public string GetParent() => currentIndex > 0 ? segments[currentIndex - 1] : null;
            public string GetChild() => currentIndex < segments.Count - 1 ? segments[currentIndex + 1] : null;

            public List<string> GetAncestors() => segments.Take(currentIndex).Reverse().ToList();
            public List<string> GetDescendants() => segments.Skip(currentIndex + 1).ToList();

            public IEnumerable<string> IterateProgressivePaths()
            {
                for (int _i = 0; _i < segments.Count; _i++)
                    yield return string.Join(SEPARATORS[0], segments.Take(_i + 1));
            }

            public IEnumerable<string> IterateRootToLeaf()
            {
                foreach (var _s in segments) yield return _s;
            }

            public IEnumerable<string> IterateLeafToRoot()
            {
                for (int _i = segments.Count - 1; _i >= 0; _i--)
                    yield return segments[_i];
            }

            public IEnumerable<string> IterateToRoot()
            {
                for (int _i = currentIndex; _i >= 0; _i--)
                    yield return segments[_i];
            }

            public IEnumerable<string> IterateToLeaf()
            {
                for (int _i = currentIndex; _i < segments.Count; _i++)
                    yield return segments[_i];
            }

            public IEnumerable<(string segment, int index, int depth)> IterateWithInfo()
            {
                for (int _i = 0; _i < segments.Count; _i++)
                    yield return (segments[_i], _i, _i);
            }

            public void ForEach(Action<string> action) => segments.ForEach(action);

            public void ForEach(Action<string, int, int> action)
            {
                for (int _i = 0; _i < segments.Count; _i++)
                    action(segments[_i], _i, _i);
            }

            public override string ToString() => GetPathToCurrent();
        }
    }
}